name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull docker image 
      run: sudo docker pull kameshdubey/cicd-pipeline:latest
    - name: delete old container if exist 
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run new container
      run: sudo docker run -d -p 8000:8000 --name cicd-pipeline-container kameshdubey/cicd-pipeline:latest
